### PR TITLE
Update hook_civicrm_tabs -> hook_civicrm_tabset

### PR DESCRIPTION
**Pull request by colemanw**
hook_civicrm_tabs() is deprecated; this fixes it by switching to the non-deprecated hook.

### CODE REVIEW

**Comment by davidknoll** [comment]
Hi @colemanw , thanks for giving this some attention. We're not using Civi at FF any more, so I'm afraid I can't put work time into testing and maintaining it, but I'm mostly happy to accept. Are you able to confirm whether this change affects version compatibility as declared in `info.xml`?

**Comment by colemanw** [comment]
@davidknoll sorry to hear that.
In terms of maintenance, I'd recommend merging #20 and then tagging `1.1`.

**Comment by highfalutin** [comment]
@davidknoll I'm actively using and expanding this extension on a client's site. I'll pull @colemanw's change into my own fork. I'm happy to publish my fork in the Civi extensions directory as the "official" CiviPoints, if you're willing to pass the baton. That should take the pressure off you to maintain an extension you no longer use. I'm happy to credit you as the original author, of course. Does that sound good?

**Comment by davidknoll** [comment]
@colemanw @highfalutin I'm happy to pass this on responsibility for this extension, please could you let me know how to make it official in the directory. Once it is official I will set this repo as archived.

I have merged both your recent changes from #19 #20 #21 but haven't tested or tagged a release. I'm hoping the changes in autogenerated Civix files are caused by Civix itself (including the CRM_Points_ExtensionUtil bit), rather than manual. (That's partly why I didn't also merge #18 just now.) There are some issues still open from me with ideas, but they are old. If/when you credit me could you also please mention Future First, as I work for them the copyright to the existing code is theirs.

Thanks!

**Comment by highfalutin** [comment]
@davidknoll I hope you've been well -- looks like I let this get buried almost two years ago! One of my clients is still using CiviPoints and I'd like to give it a little love again.

I'll ask Civi folks about how to officially take this off your hands (I never did find out how to do it). In the meantime, one thing you could do is make me a collaborator with write access on this repo.

You'd go to https://github.com/futurefirst/uk.org.futurefirst.networks.civipoints/settings/access, add lemniscus (my business name) as a collaborator, and grant write, maintain or admin status.

**Comment by highfalutin** [comment]
(Or if adding the organization name doesn't work, I guess you'd add me, highfalutin.)

**Comment by colemanw** [comment]
@highfalutin I've created https://lab.civicrm.org/extensions/civipoints and will give you maintainer rights. Once you've pushed to that repo we can simply update https://civicrm.org/extensions/civipoints to point to the gitlab repo instead of this one.
What is your GitLab user name?

**Comment by colemanw** [comment]
@highfalutin in addition I need your civicrm.org username so I can give you write access to the extension node.

**Comment by highfalutin** [comment]
Thanks @colemanw, looks like Matthieu already gave me access to the node. I just need maintainer rights to the repo on gitlab.

**Comment by colemanw** [comment]
@highfalutin I still need to know your GitLab user name!

**Comment by highfalutin** [comment]
oh sorry, I'm just "noah" there

**Comment by davidknoll** [comment]
@highfalutin @colemanw FYI I'm no longer working at @futurefirst, and AFAIK neither is my former manager. I no longer have permissions on this myself.

**Comment by colemanw** [comment]
@davidknoll could you please ask anyone with admin rights to the @futurefirst github account to archive this repo. The code has been moved so this repo is no longer needed.

**Pull request merged**
